FROM node:14
ENV NODE_ENV=development

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=3000

WORKDIR /app

COPY . /app

EXPOSE 3000

RUN yarn install

CMD [ "yarn", "dev" ]